version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: docker build -t hehk/nom_slack:$CIRCLE_BRANCH .
      - run: docker push company/app:$CIRCLE_BRANCH

