version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
        # the echo $DOCKER_PASS is used to prevent having the pass as a config arg, which will cause it 
        # to be logged
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: docker build -t hehk/lunch-slack:$CIRCLE_BRANCH .
      - run: docker push hehk/lunch-slack:$CIRCLE_BRANCH

workflows:
  version: 2
  build:
    jobs:
      - build
