// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Micro = require("micro");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

var Response = /* module */[];

function text(limit, encoding, req) {
  var options = {
    limit: Js_null_undefined.fromOption(limit),
    encoding: Js_null_undefined.fromOption(encoding)
  };
  return Micro.text(req, options);
}

var Request = /* module */[/* text */text];

function handleResponse(res, param) {
  Micro.send(res, 200, param[0]);
  return /* () */0;
}

function makeSync(handler, req, res) {
  return handleResponse(res, Curry._1(handler, req));
}

function make(handler, req, res) {
  Curry._1(handler, req).then((function (value) {
          handleResponse(res, value);
          return Promise.resolve(/* () */0);
        }));
  return undefined;
}

exports.Response = Response;
exports.Request = Request;
exports.handleResponse = handleResponse;
exports.makeSync = makeSync;
exports.make = make;
/* micro Not a pure module */
