// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("ava");

Ava.test("foo", (function (test) {
        test.pass();
        return /* () */0;
      }));

/*  Not a pure module */
