// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Micro$Nomslack = require("../bindings/micro.bs.js");

function make(param, param$1) {
  return Micro$Nomslack.make((function (req) {
                return Micro$Nomslack.Request[/* text */0](undefined, undefined, req).then((function (_value) {
                              return Promise.resolve(/* String */Block.__(0, ["Hello World"]));
                            }));
              }), param, param$1);
}

exports.make = make;
/* Micro-Nomslack Not a pure module */
